image:
  file: .gitpod.Dockerfile

ports:
  - port: 8080
    onOpen: open-preview

tasks:
  - init: |
      nvm install --lts
      nvm use --lts
      npm install -g @ionic/cli
      npm install
    command: ionic serve --host 0.0.0.0 --port 8080 --no-open
