ports:
  - port: 8100
    onOpen: open-preview
  - port: 9000-9999
    onOpen: ignore

tasks:
  - name: Update npm
    command: npm install npm@latest -g

  - name: Install global dependencies
    before: npm install -g @ionic/cli @angular/cli

  - name: Install project dependencies
    init: npm update && npm install
    command: ionic serve --host=localhost --port=8100 --disableHostCheck
